# meta_product_name: "Product Name"
# meta_title: "Product name - Product tagline"
# meta_description: "Relevant description"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards

meta_product_name: "Universaly"
meta_title: "Universaly - Une porte ouverte sur le monde"
meta_description: "Universaly est la solution qu'il vous faut pour progresser en anglais dans votre domaine de compétence"
meta_image: "social_networks_1200x630.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards